package models

import (
	"github.com/ethereum/go-ethereum/core/types"
	"gorm.io/gorm"
	"time"
)

type GameHistory struct {
	gorm.Model
	RequestID           string     // request id generated by chain link VRF
	PlayerDiscordUserId string     // discord user id
	RandomNumber        string     // random number
	Choice              int        `gorm:"comment:'游戏选择 0 偶数 | 1 奇数'"` // choice 0 even | 1 odd
	GameResult          bool       `gorm:"comment:'游戏结果'"`             // game result
	GameStatus          int        `gorm:"comment:'游戏状态 2结束，1进行中'"`    // game status
	BetValue            int64      // bet value gwei
	FinishTime          *time.Time // bet finished time 用指针可以传nil
	GuildID             string     // discord server id
	ChannelID           string     // discord channel id
	RequestRandomTxId   string     // tx id
	MainBetTxId         string     // tx id
}

type GameHistoryBo struct {
	PlayerDiscordUserId string `validate:"required"`
	Choice              uint8  `validate:"required, gt=0, lt=2"`
	BetValue            int64  `validate:"required, gt=0"`
	GuildID             string `validate:"required"`
	ChannelID           string `validate:"required"`
}

type GameHistoryRepository interface {
	CreateGame(gh *GameHistory, db *gorm.DB) error
	UpdateRequestIdByTxId(txId string, requestID string, db *gorm.DB) error
	GetGameHistoryByRequestId(requestId string, db *gorm.DB) (*GameHistory, error)
	UpdateGameAfterMainBet(game *GameHistory, db *gorm.DB) error
	GetGameHistoryByDiscordId(discordId string, db *gorm.DB) ([]GameHistory, error)
	GetLastFiveGameHistoryByDiscordId(discordId string, db *gorm.DB) ([]GameHistory, error)
}

type GameHistoryUsecase interface {
	CreateGame(bo GameHistoryBo) (*types.Transaction, error)
	UpdateRequestIdByTxId(txId string, requestID string) error
	GetGameHistoryByRequestId(requestId string) (*GameHistory, error)
	UpdateGameAfterMainBet(game *GameHistory) error
	GetGameHistoryByDiscordId(discordId string) ([]GameHistory, error)
	GetLastFiveGameHistoryByDiscordId(discordId string) ([]GameHistory, error)
}
