package models

import (
	"gorm.io/gorm"
	"time"
)

type GameHistory struct {
	gorm.Model
	RequestID           string    // request id generated by chain link VRF
	PlayerDiscordUserId string    // discord user id
	RandomNumber        int64     // random number
	Choice              int       // choice 0 even | 1 odd
	GameResult          bool      // game result
	GameStatus          int       // game status
	BetValue            int64     // bet value gwei
	FinishTime          time.Time // bet finished time
	ServerId            string    // discord server id
}
